# Generated by Django 4.0.6 on 2022-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0009_alter_promocionproducto_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Imagen de producto'),
        ),
    ]
