# Generated by Django 4.0.6 on 2022-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Venta', '0002_rename_usuarios_venta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoventa',
            name='idEstadoVenta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id estado'),
        ),
    ]
